// Copyright 2026-2027, QuarkChain.

// Receipt tests exercise pyquarkchain-compatible QKC wire bytes.

package types

import (
	"fmt"
	"reflect"
	"strings"
	"testing"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/qkc/serialize"
	"github.com/ethereum/go-ethereum/rlp"
)

const (
	receiptLegacyPostStateHex = "df227f34313c2bc4a4a986817ea46437f049873f2fca8e2b89b1ecd0f9e67a28"
	receiptRecipientHex       = "d3f86deb4a2bbf85048b3e790460c40dbab1f621"
	receiptTopic0Hex          = "a40920ae6f758f88c61b405f9fc39fdd6274666462b14e3887522166e6537a97"
	receiptTopic1Hex          = "297d6ae9803346cdb059a671dea7e37b684dcabfa767f2d872026ad0a3aba495"
	receiptBlockHashHex       = "1111111111111111111111111111111111111111111111111111111111111111"
	receiptTxHashHex          = "2222222222222222222222222222222222222222222222222222222222222222"
)

var (
	receiptBloomHex = strings.Repeat("00", 254) + "03ff"

	receiptClusterLogHex = receiptRecipientHex +
		"02" + receiptTopic0Hex + receiptTopic1Hex +
		"00000003" + "010203" +
		"000000000000000a" +
		receiptBlockHashHex +
		"00000064" +
		receiptTxHashHex +
		"000000c8"

	receiptClusterReceiptBodyHex = "00000000000003e8" +
		"0000000000000384" +
		receiptBloomHex +
		receiptRecipientHex + "0000000a" +
		"00000001" + receiptClusterLogHex

	// Generated by pyquarkchain's TransactionReceipt.serialize for success and
	// failure respectively. The success field is exactly 0x01 or empty.
	receiptClusterReceiptSuccessHex = "0101" + receiptClusterReceiptBodyHex
	receiptClusterReceiptFailureHex = "00" + receiptClusterReceiptBodyHex
	receiptLegacyClusterReceiptHex  = "20" + receiptLegacyPostStateHex + receiptClusterReceiptBodyHex

	receiptRlpSuccessHex = "f90182" +
		"01" +
		"8203e8" +
		"b90100" + receiptBloomHex +
		"f85f" +
		"f85d94" + receiptRecipientHex +
		"f842a0" + receiptTopic0Hex +
		"a0" + receiptTopic1Hex +
		"83010203" +
		"94" + receiptRecipientHex +
		"840000000a"

	// RLP receipts with a post-state root are not valid QKC receipts.
	receiptLegacyPostStateRLPHex = "f901a2" +
		"a0" + receiptLegacyPostStateHex +
		"8203e8" +
		"b90100" + receiptBloomHex +
		"f85f" +
		"f85d94" + receiptRecipientHex +
		"f842a0" + receiptTopic0Hex +
		"a0" + receiptTopic1Hex +
		"83010203" +
		"94" + receiptRecipientHex +
		"840000000a"
)

func TestReceiptQKCSerialization(t *testing.T) {
	// Generated from pyquarkchain's quarkchain.core.TransactionReceipt field order:
	// success, gas_used, prev_gas_used, bloom, contract_address, logs. There is no
	// leading tx_hash field. The nested log uses different block_hash and tx_hash.
	for _, test := range []struct {
		name    string
		encoded string
		status  uint64
	}{
		{"success", receiptClusterReceiptSuccessHex, ReceiptStatusSuccessful},
		{"failure", receiptClusterReceiptFailureHex, ReceiptStatusFailed},
	} {
		t.Run(test.name, func(t *testing.T) {
			receiptEnc := common.FromHex(test.encoded)
			var clusterReceipt ClusterTransactionReceipt
			bb := serialize.NewByteBuffer(receiptEnc)
			if err := serialize.Deserialize(bb, &clusterReceipt); err != nil {
				t.Fatal("Deserialize error: ", err)
			}
			receipt, err := clusterReceipt.ToReceipt()
			if err != nil {
				t.Fatal("ToReceipt error: ", err)
			}

			checkReceipt(t, receipt, test.status, true)

			encodedClusterReceipt, err := NewClusterTransactionReceipt(receipt)
			if err != nil {
				t.Fatal("NewClusterTransactionReceipt error: ", err)
			}
			encoded, err := serialize.SerializeToBytes(encodedClusterReceipt)
			if err != nil {
				t.Fatal("Serialize error: ", err)
			}
			if got := common.Bytes2Hex(encoded); got != common.Bytes2Hex(receiptEnc) {
				t.Errorf("serialize mismatch: got %s, want %s", got, common.Bytes2Hex(receiptEnc))
			}
		})
	}
}

func TestReceiptRLPSerialization(t *testing.T) {
	receiptRlpEnc := common.FromHex(receiptRlpSuccessHex)
	var receipt Receipt
	if err := rlp.DecodeBytes(receiptRlpEnc, &receipt); err != nil {
		t.Fatal("DecodeBytes error: ", err)
	}
	checkReceipt(t, &receipt, ReceiptStatusSuccessful, false)

	encoded, err := rlp.EncodeToBytes(&receipt)
	if err != nil {
		t.Fatal("EncodeToBytes error: ", err)
	}
	if got := common.Bytes2Hex(encoded); got != receiptRlpSuccessHex {
		t.Errorf("RLP serialize mismatch: got %s, want %s", got, receiptRlpSuccessHex)
	}
}

func TestReceiptRejectsLegacyPostStateRLP(t *testing.T) {
	var receipt Receipt
	if err := rlp.DecodeBytes(common.FromHex(receiptLegacyPostStateRLPHex), &receipt); err == nil {
		t.Fatal("legacy post-state receipt was accepted")
	}
}

func TestReceiptRejectsInvalidContractAddressLength(t *testing.T) {
	for _, size := range []int{1, common.AddressLength - 1, common.AddressLength + 1, common.HashLength} {
		t.Run(fmt.Sprintf("%d_bytes", size), func(t *testing.T) {
			fullShardKey := Uint32(0)
			encoded, err := rlp.EncodeToBytes(&receiptRLP{
				Status:               receiptStatusSuccessfulRLP,
				ContractAddress:      make([]byte, size),
				ContractFullShardKey: &fullShardKey,
			})
			if err != nil {
				t.Fatal("EncodeToBytes error: ", err)
			}
			var receipt Receipt
			if err := rlp.DecodeBytes(encoded, &receipt); err == nil {
				t.Fatalf("accepted %d-byte contract address", size)
			}
		})
	}
}

func TestReceiptRejectsLegacyPostStateQKCWire(t *testing.T) {
	var clusterReceipt ClusterTransactionReceipt
	if err := serialize.Deserialize(serialize.NewByteBuffer(common.FromHex(receiptLegacyClusterReceiptHex)), &clusterReceipt); err != nil {
		t.Fatal("Deserialize error: ", err)
	}
	if _, err := clusterReceipt.ToReceipt(); err == nil {
		t.Fatal("legacy post-state receipt was accepted")
	}
}

func TestClusterReceiptCopiesStatus(t *testing.T) {
	first, err := NewClusterTransactionReceipt(NewReceipt(false, 0))
	if err != nil {
		t.Fatal("NewClusterTransactionReceipt error: ", err)
	}
	first.Success[0] = 2

	second, err := NewClusterTransactionReceipt(NewReceipt(false, 0))
	if err != nil {
		t.Fatal("NewClusterTransactionReceipt error: ", err)
	}
	if got := common.Bytes2Hex(second.Success); got != "01" {
		t.Errorf("success status mutated through public receipt: got %s, want 01", got)
	}
}

func checkReceipt(t *testing.T, receipt *Receipt, status uint64, qkcWire bool) {
	t.Helper()
	check := func(f string, got, want interface{}) {
		if !reflect.DeepEqual(got, want) {
			t.Errorf("%s mismatch: got %v, want %v", f, got, want)
		}
	}
	check("Status", receipt.Status, status)
	check("CumulativeGasUsed", receipt.CumulativeGasUsed, uint64(1000))
	check("Bloom", common.Bytes2Hex(receipt.Bloom.Bytes()), receiptBloomHex)
	check("Len(Logs)", len(receipt.Logs), 1)
	check("Logs[0]Address", common.Bytes2Hex(receipt.Logs[0].Address.Bytes()), receiptRecipientHex)
	check("Logs[0]Topics", len(receipt.Logs[0].Topics), 2)
	check("Logs[0]Topics[0]", common.Bytes2Hex(receipt.Logs[0].Topics[0].Bytes()), receiptTopic0Hex)
	check("Logs[0]Topics[1]", common.Bytes2Hex(receipt.Logs[0].Topics[1].Bytes()), receiptTopic1Hex)
	check("Logs[0]data", common.Bytes2Hex(receipt.Logs[0].Data), "010203")
	check("ContractAddress", common.Bytes2Hex(receipt.ContractAddress.Bytes()), receiptRecipientHex)
	check("ContractFullShardKey", receipt.ContractFullShardKey, uint32(10))
	if qkcWire {
		check("Logs[0]BlockNumber", receipt.Logs[0].BlockNumber, uint64(10))
		check("Logs[0]BlockHash", common.Bytes2Hex(receipt.Logs[0].BlockHash.Bytes()), receiptBlockHashHex)
		check("Logs[0]TxIndex", receipt.Logs[0].TxIndex, uint(100))
		check("Logs[0]TxHash", common.Bytes2Hex(receipt.Logs[0].TxHash.Bytes()), receiptTxHashHex)
		check("Logs[0]Index", receipt.Logs[0].Index, uint(200))
		check("GasUsed", receipt.GasUsed, uint64(100))
	}
}
